### PR TITLE
feat : initing responsive navbar using responsive code js

### PR DESCRIPTION
**Pull request by alifertah**

### CODE REVIEW

**Review by Hackermans007 — CHANGES_REQUESTED** [review]
Add Accessoiar in drop down menu.
Add hover effect.
not user frendly .
not eye apealing. 
khdm m3ana asa7bi .

**Review by Hackermans007 — APPROVED** [review]
NICE

**Review by Elgadisalma — APPROVED** [review]

**Comment by Hackermans007** [comment]
Nav-bar not shoing in all pages!!!!!!!

**Review by Hackermans007 — APPROVED** [review]
Good boy.

**Pull request merged**
